from rooms import Room
from guests import Guest
room = Room()
guest = Guest()
#room.insert(101, 2000, "presidential suite", "yes")
#room.insert(110, 4000, "suite")
#guest.check_in('M', 9913, 102)
#guest.check_in('P', 9913, 101)
#guest.check_in('JD', 9913, 105)
#room.check_out(101)
#room.update(102, 1800, "suite", "yes")
#room.check_out(102)
#room.check_in(101)
#guest.check_out_by_name("M")
#guest.check_out(102)
#guest.display_current_guests()
#guest.display_current_guests_by_room(102)
guest.display()
room.display()
#oom.display()
#room.display_available_rooms()
#room.check_in(101)
#print(room.check_availibility(101))
#room.display()

    
